// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Mejora_Continua.Models;

public partial class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ContinuousImprovementCategory> ContinuousImprovementCategory { get; set; }

    public virtual DbSet<ContinuousImprovementChampions> ContinuousImprovementChampions { get; set; }

    public virtual DbSet<ContinuousImprovementIdeas> ContinuousImprovementIdeas { get; set; }

    public virtual DbSet<ContinuousImprovementStatus> ContinuousImprovementStatus { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ContinuousImprovementCategory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Continuo__3214EC076B9225B8");

            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("name");
        });

        modelBuilder.Entity<ContinuousImprovementChampions>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Continuo__3214EC070DAFB353");

            entity.Property(e => e.Email)
                .HasMaxLength(80)
                .IsUnicode(false)
                .HasColumnName("email");
            entity.Property(e => e.Name)
                .HasMaxLength(70)
                .IsUnicode(false)
                .HasColumnName("name");
        });

        modelBuilder.Entity<ContinuousImprovementIdeas>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Continuo__3214EC07ECEE4DD4");

            entity.Property(e => e.CurrentSituation)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("currentSituation");
            entity.Property(e => e.FullName)
                .HasMaxLength(300)
                .IsUnicode(false)
                .HasColumnName("fullName");
            entity.Property(e => e.IdeaDescription)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("ideaDescription");
            entity.Property(e => e.RegistrationDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("registrationDate");
            entity.Property(e => e.StatusId).HasColumnName("statusId");
            entity.Property(e => e.WorkArea)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("workArea");

            entity.HasOne(d => d.Status).WithMany(p => p.ContinuousImprovementIdeas)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__Continuou__statu__6754599E");

            entity.HasMany(d => d.Category).WithMany(p => p.Idea)
                .UsingEntity<Dictionary<string, object>>(
                    "IdeaCategory",
                    r => r.HasOne<ContinuousImprovementCategory>().WithMany()
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__IdeaCateg__Categ__6B24EA82"),
                    l => l.HasOne<ContinuousImprovementIdeas>().WithMany()
                        .HasForeignKey("IdeaId")
                        .HasConstraintName("FK__IdeaCateg__IdeaI__6A30C649"),
                    j =>
                    {
                        j.HasKey("IdeaId", "CategoryId").HasName("PK__IdeaCate__5FB111A31C78975E");
                    });

            entity.HasMany(d => d.Champion).WithMany(p => p.Idea)
                .UsingEntity<Dictionary<string, object>>(
                    "IdeaChampion",
                    r => r.HasOne<ContinuousImprovementChampions>().WithMany()
                        .HasForeignKey("ChampionId")
                        .HasConstraintName("FK__IdeaChamp__Champ__6EF57B66"),
                    l => l.HasOne<ContinuousImprovementIdeas>().WithMany()
                        .HasForeignKey("IdeaId")
                        .HasConstraintName("FK__IdeaChamp__IdeaI__6E01572D"),
                    j =>
                    {
                        j.HasKey("IdeaId", "ChampionId").HasName("PK__IdeaCham__DCE0CD312423FAF3");
                    });
        });

        modelBuilder.Entity<ContinuousImprovementStatus>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Continuo__3214EC079125E0D3");

            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("name");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}