// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Mejora_Continua.Models;

public partial class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ContinuousImprovementCategory> ContinuousImprovementCategory { get; set; }

    public virtual DbSet<ContinuousImprovementChampions> ContinuousImprovementChampions { get; set; }

    public virtual DbSet<ContinuousImprovementIdeas> ContinuousImprovementIdeas { get; set; }

    public virtual DbSet<ContinuousImprovementStatus> ContinuousImprovementStatus { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ContinuousImprovementCategory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pk_StatusCategory");

            entity.Property(e => e.Name)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasColumnName("name");
        });

        modelBuilder.Entity<ContinuousImprovementChampions>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pk_Champions");

            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("email");
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("name");
        });

        modelBuilder.Entity<ContinuousImprovementIdeas>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pk_ContinuousImprovementIdeas");

            entity.Property(e => e.CurrentSituation)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("currentSituation");
            entity.Property(e => e.FullName)
                .HasMaxLength(70)
                .IsUnicode(false)
                .HasColumnName("fullName");
            entity.Property(e => e.IdeaDescription)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("ideaDescription");
            entity.Property(e => e.RegistrationDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("registrationDate");
            entity.Property(e => e.StatusId)
                .HasDefaultValue(1)
                .HasColumnName("statusId");
            entity.Property(e => e.WorkArea)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("workArea");

            entity.HasOne(d => d.Status).WithMany(p => p.ContinuousImprovementIdeas)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_ContinuousImprovementIdeasStatus");

            entity.HasMany(d => d.Category).WithMany(p => p.Idea)
                .UsingEntity<Dictionary<string, object>>(
                    "IdeaCategory",
                    r => r.HasOne<ContinuousImprovementCategory>().WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__IdeaCateg__Categ__498EEC8D"),
                    l => l.HasOne<ContinuousImprovementIdeas>().WithMany()
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__IdeaCateg__IdeaI__489AC854"),
                    j =>
                    {
                        j.HasKey("IdeaId", "CategoryId").HasName("PK__IdeaCate__5FB111A3AB1E8DA1");
                    });

            entity.HasMany(d => d.Champion).WithMany(p => p.Idea)
                .UsingEntity<Dictionary<string, object>>(
                    "IdeaChampion",
                    r => r.HasOne<ContinuousImprovementChampions>().WithMany()
                        .HasForeignKey("ChampionId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__IdeaChamp__Champ__4D5F7D71"),
                    l => l.HasOne<ContinuousImprovementIdeas>().WithMany()
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__IdeaChamp__IdeaI__4C6B5938"),
                    j =>
                    {
                        j.HasKey("IdeaId", "ChampionId").HasName("PK__IdeaCham__DCE0CD3131D199EB");
                    });
        });

        modelBuilder.Entity<ContinuousImprovementStatus>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("pk_StatusContinuous");

            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("name");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}