// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Mejora_Continua.Models;

public partial class ContinuousImprovementIdeas
{
    public int Id { get; set; }

    public string FullName { get; set; }

    public string WorkArea { get; set; }

    public string CurrentSituation { get; set; }

    public string IdeaDescription { get; set; }

    public int StatusId { get; set; }

    public DateTime? RegistrationDate { get; set; }

    [NotMapped]
    public List<int> CategoryIds { get; set; } = new List<int>();

    [NotMapped]
    public List<string> Names { get; set; } = new List<string>();

    public virtual ContinuousImprovementStatus Status { get; set; }

    public virtual ICollection<ContinuousImprovementCategory> Category { get; set; } = new List<ContinuousImprovementCategory>();

    public virtual ICollection<ContinuousImprovementChampions> Champion { get; set; } = new List<ContinuousImprovementChampions>();
}