// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Mejora_Continua.Models;

public partial class ContinuousImprovementCategory
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<ContinuousImprovementIdeas> Idea { get; set; } = new List<ContinuousImprovementIdeas>();
}