// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Mejora_Continua.Models;

public partial class ContinuousImprovementChampions
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public virtual ICollection<IdeaChampion> IdeaChampion { get; set; } = new List<IdeaChampion>();
}