// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Mejora_Continua.Models;

public partial class ContinuousImprovementIdeas
{
    public int Id { get; set; }

    public string FullName { get; set; }

    public string WorkArea { get; set; }

    public string CurrentSituation { get; set; }

    public string IdeaDescription { get; set; }

    public DateTime? RegistrationDate { get; set; }

    public int? StatusId { get; set; }

    public virtual ICollection<IdeaCategory> IdeaCategory { get; set; } = new List<IdeaCategory>();

    public virtual ICollection<IdeaChampion> IdeaChampion { get; set; } = new List<IdeaChampion>();

    public virtual ContinuousImprovementStatus Status { get; set; }
}