// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Mejora_Continua.Models;

public partial class IdeaChampion
{
    public int IdeaId { get; set; }

    public int ChampionId { get; set; }

    public virtual ContinuousImprovementChampions Champion { get; set; }

    public virtual ContinuousImprovementIdeas Idea { get; set; }
}