// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Mejora_Continua.Models;

public partial class IdeaCategory
{
    public int IdeaId { get; set; }

    public int CategoryId { get; set; }

    public virtual ContinuousImprovementCategory Category { get; set; }

    public virtual ContinuousImprovementIdeas Idea { get; set; }
}